version: '3.0'
services:
  java-maven-app:
    image: ${IMAGE} # Use the IMAGE env variable set in the server-cmds.sh file
    ports:
      - "8080:8080"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"